"""Update stock

Revision ID: cce9272f285c
Revises: f551f5cf46e0
Create Date: 2026-03-24 17:30:34.102669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cce9272f285c'
down_revision = 'f551f5cf46e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbound_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False))

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_column('version')

    with op.batch_alter_table('inbound_orders', schema=None) as batch_op:
        batch_op.drop_column('version')

    # ### end Alembic commands ###
