"""Create inbound order and items

Revision ID: f551f5cf46e0
Revises: 434fbf95b405
Create Date: 2026-03-23 16:37:02.440186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f551f5cf46e0'
down_revision = '434fbf95b405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbound_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('received_date', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'CANCELLED', name='inboundstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inbound_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inbound_order_id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['inbound_order_id'], ['inbound_orders.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_item_id'], ['purchase_order_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('received_quantity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False))

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_column('inbound_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inbound_date', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.drop_column('version')
        batch_op.drop_column('received_quantity')

    op.drop_table('inbound_items')
    op.drop_table('inbound_orders')
    # ### end Alembic commands ###
